### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by paulhobbel** [butterproject/butter-android#1]
@se-bastiaan we should add some more try segements to fix the app crash if a provider isnt available

**Comment by se-bastiaan** [comment]
try segments?

**Comment by insertc0in** [comment]
Whichever prevents the app from crashing would be good.

**Comment by se-bastiaan** [comment]
It doesn't crash, afaik

**Comment by paulhobbel** [comment]
@se-bastiaan it would crash if vodo was offline

**Comment by se-bastiaan** [comment]
Is it still doing this?

**Comment by paulhobbel** [comment]
Guess not
