### ISSUE TITLE
Android anime error

### ISSUE THREAD

**Issue by PingouinArmy** [butterproject/butter-android#105]
App Version:  0.2.8
Android version:  5.1.1

Expected behaviour: Load the anime section
Actual behaviour: Tell me something went wrong and doesn't show any anime at all in the section 

Steps to repoduce the behaviour: 
1)open the app 
2)go to the anime section 
3) nothing shows up

Respectfully
A world wide web user

**Comment by xaiki** [comment]
we have no anime
