### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by se-bastiaan** [butterproject/butter-android#12]

**Comment by blazsolar** [comment]
I'm closing this as test should be part of every new feature.

**Comment by xaiki** [comment]
this was intented to track the lacking unit-tests for all the old features where it never was implemented.

**Comment by blazsolar** [comment]
Majority of stuff everything will be rewritten so as we go on we will have more and more coverage. In my opinion this is good enough. Problem is that the code that is written at the moment is not really testable. So it would be really hard to write tests for old functionality.

**Comment by xaiki** [comment]
ok, if this is a total rewrite wouldn't it make sense to actually start in a new repo ?

**Comment by blazsolar** [comment]
Maybe it would make sense if new version would have limited functionalities. But since we want all features in 1.0.0 this does not really make sense as code is not that bad it couldn't be refactored. 

Also we are already almost done with MVP which one of two biggest parts of refactor.
