### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by GeorgeSkyway** [butterproject/butter-android#122]
App Version:  0.2.8
Android version:  6.0

Actual behaviour: App crashes after buffering is finished. seems that there is an issue with the player.an anybody advise me solution I tested with my LG G4 and some other virtual phones from android studio

**Comment by aldoborrero** [comment]
@GeorgeSkyway Can you provide the stacktrace? Would be helpful!

**Comment by aldoborrero** [comment]
I'll mark this issue as closed. Feel free to reopen it if something arises again!
