### ISSUE TITLE
Should we continue to support Android 15?

### ISSUE THREAD

**Issue by aldoborrero** [butterproject/butter-android#124]
Is necessary to support this older version of Android? Wouldn't be better to increase the minimum version to 16?

According to the ([Android Dashboard graph](https://developer.android.com/about/dashboards/index.html)) we can safely upgrade to 16 without dropping too much users.

What do you think?

**Comment by blazsolar** [comment]
I'm all for bumping version to 16.

**Comment by se-bastiaan** [comment]
imo, 19 would even be possible. But 16 is good.

**Comment by aldoborrero** [comment]
Then we settle to 16 and later if we needed we can go 19 upwards

**Comment by blazsolar** [comment]
This was resolved with #125 PR.
