### ISSUE TITLE
Should we add checkstyle and standardise the whole codebase?

### ISSUE THREAD

**Issue by aldoborrero** [butterproject/butter-android#126]
While I was getting familiar with the whole codebase I thought that code seems to be different in terms of code style.

So I thought that it could be a good idea to integrate checkstyle into the project (at least to have a tool that warns us when using non standard ways of formatting the code).

Here I left some screenshots:

<img width="1912" alt="screen shot 2017-03-15 at 00 07 52" src="https://cloud.githubusercontent.com/assets/82811/23926264/830a0d2e-0913-11e7-9eb2-62fd438b2218.png">

<img width="1895" alt="screen shot 2017-03-15 at 00 08 44" src="https://cloud.githubusercontent.com/assets/82811/23926281/97cbb91a-0913-11e7-96d1-d295cabd29b4.png">

If you believe that this is worth it I'll do a PR.

PD: Should we use a formatting style like [Square Android Styles](https://github.com/square/java-code-styles) to standardise the whole code base? (I'm already using it on other projects and is great but with max 140 chars instead of 100). 

Here is code before formatting:

<img width="1920" alt="screen shot 2017-03-15 at 00 10 08" src="https://cloud.githubusercontent.com/assets/82811/23926317/c71463b6-0913-11e7-9727-a2cadd34d569.png">

Here is code after formatting (as you can see instead of using 4 tabs now is using 2 which gives you more space to add more code without loosing legibility):

<img width="1920" alt="screen shot 2017-03-15 at 00 10 36" src="https://cloud.githubusercontent.com/assets/82811/23926328/d8a7c1f4-0913-11e7-89da-9ca2e8a767a9.png">

What do you think also about this?

**Comment by blazsolar** [comment]
This is definitely something we want to do. But at the moment this is a low priority, because there are more important issues to resolve. If you want to do it you can tho, but be sure that this checks are then part of CI builds. I personally usually use [Soter](https://github.com/kaminomobile/soter) plugin for that. 

I personally am not a fan of Square code styling, it differs to much from Oracles/Suns styles. This would be something we have to agree on before works is started on . I can prepare a proposal/checkstyle configuration for this.

**Comment by aldoborrero** [comment]
Nice! 

Yeah, I know that the formatting is pretty different, I can prepare a feature-branch with the changes I already did (and later we can continue moving things forward if needed).

Another option is using Google code styling for Java (which is a more standard way of formatting [source](https://google.github.io/styleguide/javaguide.html)).

**Comment by aldoborrero** [comment]
Are you guys available in irc to have a quick chat? @xaiki @blazsolar in order to coordinate better efforts (maybe we can prepare boards with milestones to create a set of task that people can work with).

Currently, there's one in popcorn-android with milestone 0.3.0 but some of that tasks are not tracked "correctly" (so I don't know how the progress is going and where I can jump to help).

**Comment by blazsolar** [comment]
Googles formatting is more to my liking. We can start from that one and makes some modifications as it is pretty strict. You can open PR with changes that you already did and we can go from there.

We use slack for communication maybe @xaiki can invite you.

**Comment by aldoborrero** [comment]
Here we have a [checkstyle](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) that enables Google style.

Later, I'll apply those and I'll upload them to feature branch!

**Comment by aldoborrero** [comment]
Added a proposal to discuss the new code style in [Issue #133 ](https://github.com/butterproject/butter-android/issues/133)! I'm closing this one!
