### ISSUE TITLE
Proposal for code style

### ISSUE THREAD

**Issue by aldoborrero** [butterproject/butter-android#133]
Now that checkstyle ([PR #128](https://github.com/butterproject/butter-android/pull/128) and PR [#131](https://github.com/butterproject/butter-android/pull/131)) has currently been merged into the main development branch I would like to propose a set of fixed rules, the idea is to discuss this list to reach a consensus that later will be applied and "forced" into the code that way we can minimise merge conflicts, we have better predictable code and would allow faster reviewal in case new contributors jumps in to help:

For JAVA:

- Max lines: 120 (for me would be better to have 140 if possible, today we have wide screen monitors and the less line breaks the better)
- Indentation: 4 spaces - continuation 8 spaces (Image 2)
- Final usage by default (Image 3)
- Order of members: Static fields, Instance fields, Static methods, Constructors, Instance methods, Static inner classes, Inner classes (Image 4)
- Grouping roules: Getters / Setters together - Overriden methods together - Dependent methods together: breath first order (Image 5)
- Imports: Single class import, Insert imports for inner classes, avoid using imports with * (Image 6)

Image 2:
<img width="315" alt="screen shot 2017-03-19 at 23 47 44" src="https://cloud.githubusercontent.com/assets/82811/24085538/8bfd6c16-0cfe-11e7-87f5-1356aaa0c6d5.png">

Image 3:
<img width="310" alt="screen shot 2017-03-19 at 23 48 59" src="https://cloud.githubusercontent.com/assets/82811/24085548/a6b27434-0cfe-11e7-91b5-a271ee7718e5.png">

Image 4:
<img width="173" alt="screen shot 2017-03-19 at 23 49 26" src="https://cloud.githubusercontent.com/assets/82811/24085561/cfe8e8f6-0cfe-11e7-8382-fe388ddfd759.png">

Image 5:
<img width="665" alt="screen shot 2017-03-19 at 23 54 49" src="https://cloud.githubusercontent.com/assets/82811/24085634/a0029c3a-0cff-11e7-8fc0-c7415f9be033.png">

Image 6:
<img width="598" alt="screen shot 2017-03-19 at 23 56 52" src="https://cloud.githubusercontent.com/assets/82811/24085649/e6f6a8ca-0cff-11e7-809b-a2240560cf54.png">

For XML:

- Indentation: 4 spaces (Image 7)
- Max lines: 120 (but I would opt for 140)
- Ordering of properties predictable (where android:id is first, android:layout_height is second and so on) to minimize conflict merges. (Image 8)

Image 7:
<img width="249" alt="screen shot 2017-03-20 at 00 00 12" src="https://cloud.githubusercontent.com/assets/82811/24085673/3cb4b20c-0d00-11e7-8097-b7846fb70a04.png">

Image 8:
<img width="406" alt="screen shot 2017-03-20 at 00 01 11" src="https://cloud.githubusercontent.com/assets/82811/24085682/6527578a-0d00-11e7-980d-bf751cc46631.png">

For Gradle:

- Indentation: 4 spaces - continuation 8 (Image 9)

<img width="390" alt="screen shot 2017-03-20 at 00 02 08" src="https://cloud.githubusercontent.com/assets/82811/24085689/841148a4-0d00-11e7-81fd-eb4f9a35e10a.png">

Write your opinions and thoughts!

**Comment by blazsolar** [comment]
Seams reasonable enough. I'll add code style to #131 PR.
