### ISSUE TITLE
Update VLC player

### ISSUE THREAD

**Issue by blazsolar** [butterproject/butter-android#137]

**Comment by aldoborrero** [comment]
VLC Player or switch to ExoPlayer?

**Comment by blazsolar** [comment]
Something to discuss. We should check that it contains all functionalities that we require. Stuff like multiple audio tracks and soon.

**Comment by aldoborrero** [comment]
As stated [here](https://github.com/popcorn-official/popcorn-android/issues/81) user @cooliobr has mentioned:

> @team-pct ExoPlayer use ffmpeg as audio renderer, then no problem with audio or sub.
https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/README.md

**Comment by aldoborrero** [comment]
Also, another possible option is to try to continue using VLC libs but using our own fork, forking [this repository in the butterproject](https://github.com/mrmaffen/vlc-android-sdk/blob/master/build.gradle) and publishing to jitpack (that way we can track what version we are using at any point).

Keep in mind that that repo contains logic to pull sources from VLC android git and update accordingly.

**Comment by aldoborrero** [comment]
After keeping an eye to the VLC android source code, I suggest that the best option for now is to stick to VLC updating us the [android-sdk-version ](https://github.com/mrmaffen/vlc-android-sdk/blob/master/build.gradle).

I think that will resolve a lot of bugs that are cropping around and the man effort to do a big rewrite is not needed as the code is already in place.

At a post 1.0 release we can investigate if is better to add support to ExoPlayer.

**Comment by aldoborrero** [comment]
There have been work done on [https://github.com/aldoborrero/vlc-android-sdk](https://github.com/aldoborrero/vlc-android-sdk) but I found some small issues I have to tackle about before creating an stable release. 

Working on it! I'll keep this issue updated.

**Comment by xaiki** [comment]
if you want we can import that repo into butterproject ?

**Comment by blazsolar** [comment]
I would leave it separate. Few reasons for that. 

 - We can easily merge changes from original repo and contribute back to it.
 - We can over time provide solid implementation of VLC for Android library that other developers can use on their own project.
 - We decouple project a bit. That should make compiling a bit faster when developing (in theory)

**Comment by blazsolar** [comment]
Oh @xaiki, you mean from `aldoborrero/vlc-android-sdk`. Yeah we will do that through PRs

**Comment by blazsolar** [comment]
https://github.com/karanvs/ExVidPlayer?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=5645 something to look at

**Comment by blazsolar** [comment]
This was closed by #177
