### ISSUE TITLE
Subtitles should be handled by VLC

### ISSUE THREAD

**Issue by blazsolar** [butterproject/butter-android#174]
At the moment we are downloading, parsing and displaying subtitles ourself. Since VLC has that functionality already implemented we should move it there. Downloading should still be done by us.

**Comment by se-bastiaan** [comment]
Unless the functionality to change the subtitle size and colour was implemented in VLC for Android you probably don't want to let the player handle it if you don't want to lose functionality

**Comment by blazsolar** [comment]
Haven't looked much into this, but yes I agree with you.
