### ISSUE TITLE
Bug: choosing a genre doesn't do anything 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [butterproject/butter-android#21]
It just gets marked and doesn't do anything

**Comment by se-bastiaan** [comment]
The VodoProvider does not have any genres.

**Comment by AndroidDeveloperLB** [comment]
So why show them?
What is this then:
![device-2016-02-28-232600](https://cloud.githubusercontent.com/assets/5357526/13381990/c13623ca-de72-11e5-8f4e-e9110ed97d6a.png)
?

The genres exist on all nav-drawer items (anime, movies and tv shows).

**Comment by se-bastiaan** [comment]
> all nav-drawer items (anime, movies and tv shows)
We only have one drawer item in the current source and that's movies. This means that you're not using Butter.

**Comment by AndroidDeveloperLB** [comment]
But it has a link to go here for issues...
i thought it was weird...
anyway, thanks.
if the nav-drawer only has a single item of  movies, why have it at all?
