### ISSUE TITLE
TorrentStream license

### ISSUE THREAD

**Issue by se-bastiaan** [butterproject/butter-android#254]
Since you've disable issues on your TorrentStream-Android repo I figured this would be the right place to put this.

It's cool that you forked the repository, but according to the Apache 2 license that the code is distributed under you have to apply the same license and _preserve_ all original copyright, patent, trademark and attribution notices in all unmodified parts. It looks like you've only changed the package and added a  CI file for circle. So it would be nice if you'd follow the license and keep my copyright in the headers.

In any case, if you have things that could be improved: PRs are welcome :)
I'm updating the library every once in a while to target newer Android versions or to use the latest jlibtorrent release etc.

Good to see that you're still working to improve this mess :p

**Comment by blazsolar** [comment]
Hi,

sorry for that, i'll revert the license part changes so it to follow Apache 2 license. 

As for PRs, the plan is to rewrite this library in the future so it probably won't follow the same direction that your library.

**Comment by se-bastiaan** [comment]
Thanks!

That's sad, I don't see how your change of direction might not benefit anyone else using TorrentStream-Android and thus requiring a fork.  I'm open for anything, if the basic functionality (= sequentially download (a) torrent file(s)) stays the same.

**Comment by blazsolar** [comment]
Hi, this was resolved as discussed.
