### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by Sanchit43** [butterproject/butter-android#278]
I Just want butter version of video player for android any repo to directly use it.
Thank You

**Comment by blazsolar** [comment]
At the moment latest `develop` uses  vlc 3.0. For now that is the only video player that we support. We are looking on experimenting with ExoPlayer, but there is no timeline for it yet.

Do you have any specific issues that we can look into?

**Comment by Sanchit43** [comment]
I just want to know how can i impliment butter project player in any app i want to do so just the player with subtitle pack how can i do it any guide.

Thank You for this awesome project you helped many of us with your code.

**Comment by blazsolar** [comment]
What do you mean by player? Just the video player or also a downloading part?

**Comment by Sanchit43** [comment]
Just The Video Player for android to Play Video from directory and  i compiled the package for android app it crashes on media played from external i will fix and push it back no issues just help me with player Implimentation thank you

**Comment by blazsolar** [comment]
We use [vlc sdk](https://github.com/butterproject/vlc-android-sdk). It is basically just extracted video part from VLC. How to implement it. You can check our code or https://code.videolan.org/videolan/libvlc-android-samples

**Comment by Sanchit43** [comment]
Ooh thank you can you please tell me which class and modules in your project contains player activity for layout and subs ad on

**Comment by blazsolar** [comment]
[AbsPlayerFragment](https://github.com/butterproject/butter-android/blob/develop/mobile/src/main/java/butter/droid/ui/player/abs/AbsPlayerFragment.java) is the majority of it, in combination with [presenter](https://github.com/butterproject/butter-android/blob/develop/base/src/main/java/butter/droid/base/ui/player/base/BaseVideoPlayerPresenterImpl.java)

**Comment by Sanchit43** [comment]
Ooh thank you so much for your help will check it out can you please tell me where can i donate for this project.

**Comment by blazsolar** [comment]
No problem. For donations we currently only accept bitcoins here: `1Neb2kGPSgay4ETGcqFdXA7xjV8eqgjMJZ`.
