### ISSUE TITLE
Why is poster used as background?

### ISSUE THREAD

**Issue by israelidanny** [butterproject/butter-android#284]
In various places in the app, poster is shown instead of backdrop to act as a background. Why would that make sense?

Example:
https://github.com/butterproject/butter-android/blob/4186e090e30f40ee928f066d83e6825f64c225d1/tv/src/main/java/butter/droid/tv/ui/detail/TVMediaDetailPresenterImpl.java#L33

**Comment by blazsolar** [comment]
Probably a mistake. Something to go through and unify.

**Comment by blazsolar** [comment]
This was fixed and merged into develop.
