### ISSUE TITLE
Crash after streaming one torrent, it's impossible to stream a second one without closing the app first

### ISSUE THREAD

**Issue by israelidanny** [butterproject/butter-android#287]
App Version:  Android TV

Expected behaviour:
Ability to start a stream, leave it & go to another one

Actual behaviour (Steps to reproduce the behaviour):
1. Start a stream
2. Press "Back"
3. Pick another stream
4. The player crashes and goes back to the detail screen

**Comment by blazsolar** [comment]
This was addressed recently and should be merged shortly into develop.

**Comment by blazsolar** [comment]
Resolved and in develop.
