### ISSUE TITLE
is this only for movies??

### ISSUE THREAD

**Issue by Samuelincoom** [butterproject/butter-android#293]
is butter project only for movies?? I see only old movies after building the APK.. how do i connect to the api server to get both LATEST Series and LATEST Movies

**Comment by blazsolar** [comment]
Butter uses VODO for getting media. But if you want to get media from any different source you can always fork project and create your own `MediaProvider`

**Comment by Samuelincoom** [comment]
thanks...  Any good suggestions though?

**Comment by blazsolar** [comment]
For movie sources? Maybe you should look into fork of butter project. One of most popular is [popcorntime](https://github.com/popcorn-official/popcorn-android)

**Comment by Samuelincoom** [comment]
wow!! thanks... Does this mean that popcorntime does not need any providers?? as in i can immediately start watching TV series after building android project in android studio??

**Comment by blazsolar** [comment]
Yes, that would be the case.

**Comment by Samuelincoom** [comment]
Thanks...   I am in the process of building it as we speak.. Although the gradle version is old and finding some difficulties with version conflicts...
I am sure i can contribute to make it better

**Comment by blazsolar** [comment]
Yes, it has been a while since stuff was updated due to lack of contributors. 

Contributions always welcome 😄

**Comment by Samuelincoom** [comment]
This is my first time using these opensource tv solutions.. is there one for TV channels?? Lets say a popcorntime with providers for live tv channels and not just TV series...   where i can build myself just like popcorntime

**Comment by blazsolar** [comment]
not that i am aware of.

**Comment by Samuelincoom** [comment]
i have been able to get the popcorntime build 100% working.. but it looks like it only downloads torrent.. i havent be able to get it streaming torrent or playing video live... whats wrong?
