### ISSUE TITLE
Movies and Series not shown

### ISSUE THREAD

**Issue by davidgamez604** [butterproject/butter-android#294]
App Version:  butter-android
Android version:  0.5.6

Expected behaviour:
Actual behaviour:

Steps to repoduce the behaviour:

I am using android studio, but when I generate the apk it show only few movies, what I should do to show the movies and series as shown in popcorn Time? 
Please help
Thanks

**Comment by blazsolar** [comment]
Hi @davidgamez604,

so this is NOT PopcornTime and does not have the same content as it does. If you build debug version (which is what it happens in AS by default) you will only get movies used for testing. On the other hand, if you build release version you will get a full list of movies available on Butter. But know that this still won't be the same list as on PopcornTime.

**Comment by davidgamez604** [comment]
Thanks for your reply, I fix that by downloading original popcorn time
source code
just I have another question please, how can I change selected item color
from gray to another color?
