### ISSUE TITLE
No covers in Pelis Magnet

### ISSUE THREAD

**Issue by manserra** [butterproject/butter-android#32]
App Version: 0.2.9-armeabi-v7a
Android version:  4.4.2

Expected behaviour:
Actual behaviour:

Steps to repoduce the behaviour:

1. ... Open aplication on no image of covers is shown in my Bq Aquaris E10
2. ... Other tablet, Bq Maxwell 2 plus show covers. 
3. ... Two tablets are in the same net using the same router. 
4. ... My sister has another tablet,  Bq Aquaris E10, I installed the same version of Pelis Magnet in her tablet.. In his tablet,  covers are shown.  But she is conected to another internet provider.

**Comment by se-bastiaan** [comment]
0.2.9-armeabi-v7a? We don't have any releases yet? What is 'Pelis Magnet'?

**Comment by se-bastiaan** [comment]
Okay. Found what it is. We're not related to this application at all. File a bug report in their issue tracker, if they have one.

**Comment by manserra** [comment]
Ok.
Finally I solve the problem. It was that in my tablet I have installed a ads blocker and I supose it blocks the ip address where the aplication looks for the covers.

I cleaned the hosts file and the aplication works fine.

Thanks for your support.
