### ISSUE TITLE
Switch to MVP/MVVM

### ISSUE THREAD

**Issue by se-bastiaan** [butterproject/butter-android#5]
The app needs more structure on the UI side. So using MVP or MVVM could improve it a lot.

**Comment by aldoborrero** [comment]
Is this issue completely done? 

Checking the code in mobile folder I would say that mostly yes. If not, any help wanted to finish it? @se-bastiaan @xaiki @blazsolar

**Comment by blazsolar** [comment]
No this is not yet done. At the moment I am working on media list and search screens. The easiest way for you to jump on this would be to port `NavigationDrawerFragment` to MVP.

**Comment by aldoborrero** [comment]
References to related PRs:

- [PR134](https://github.com/butterproject/butter-android/pull/134)
- [PR130](https://github.com/butterproject/butter-android/pull/130)
- [PR135](https://github.com/butterproject/butter-android/pull/135)
- [PR129](https://github.com/butterproject/butter-android/pull/129)
- [PR127](https://github.com/butterproject/butter-android/pull/127)
- [PR120](https://github.com/butterproject/butter-android/pull/120)
- [PR117](https://github.com/butterproject/butter-android/pull/117)
- [PR116](https://github.com/butterproject/butter-android/pull/116)
- [PR115](https://github.com/butterproject/butter-android/pull/115)
- [PR114](https://github.com/butterproject/butter-android/pull/114)
