### ISSUE TITLE
Popcorn time subtitles

### ISSUE THREAD

**Issue by orlahorsten** [butterproject/butter-android#57]
When i go to settings and change the size of the subtitles, it won't change when i watch a movie or an episode. I already tried it when i closed the app and restarted it, but it didn't help. I also tried to change te subtitle's size when i've opened a movie (while watching) but that wouldn't work either. It automatically went back to the original size. How can this problem be solved?

**Comment by babywin** [comment]
Same problem here

**Comment by orlahorsten** [comment]
It so annoying, right? Send me something if u find a solution haha

**Comment by babywin** [comment]
Yeah man this make the subtitles unreadable

**Comment by orlahorsten** [comment]
Yes it does! But I'm "glad" I'm not the only one with this problem...

**Comment by babywin** [comment]
Yeah. I don't know why some se-bastiaan are closing our threads over subtitles.

**Comment by orlahorsten** [comment]
Well I saw it too... But what does that mean? Can't other people read this anymore or? (Sorry I've never used github before haha)

**Comment by se-bastiaan** [comment]
I actually do read everything. And everyone else still can too.

Problem is that this issue can't be happening in our application, since we haven't released anything yet. If anyone else is using our codebase then they're welcome to fix any issues they find, but I'm not going to do it for them.
