### ISSUE TITLE
Subtitles do not change size and font over Chromecast

### ISSUE THREAD

**Issue by babywin** [butterproject/butter-android#58]
App Version:  0.2.8 - armeabi-v7a
Android version:  6.0.1

Expected behaviour: Change subtitles size while cast to chromecast. Also add an option to change the font.
Actual behaviour: Subtitles size do not always change their size and also there is no option to do this while casting to chromecast. Also there is no option to change the font for a serif one.

Steps to repoduce the behaviour:

1. Change the subtitles size on preferences
2. Watch a movie with subtitles and cast to chromecast
3. Remember the actual subtitles size showed on screen
4. Stop casting to chromecast
5. Increase the font size of the subtitle
6. Cast again
7. Compare the new size of the subtitle with the las one
8. There is no increase of the subtitle size at all

**Comment by se-bastiaan** [comment]
I didn't know we released an application with version 0.2.8. Hell, I didn't even know we released anything.

But, just fyi. This is not possible at all. 0% chance of success, technically.

**Comment by babywin** [comment]
Why you close your issues if you are so little informed of the released versions?

It is not impossible. In fact it is very simple. The PopCornTime.SE version has had that option for a long time. FYI...

**Comment by se-bastiaan** [comment]
We are not Popcorn Time.
