### ISSUE TITLE
Popcorn time chromecast not working

### ISSUE THREAD

**Issue by chelseyim** [butterproject/butter-android#59]
App Version:  
Android version:  

Expected behaviour:
Actual behaviour: stopped it the middle of watching sherlock Holmes, exited the movie, now won't let me stream to the chromecast. 
It does it with every movie now.

Steps to repoduce the behaviour:

1. Load video until after its buffered
2. Click the square thing to stream to chromecast. It will stop and not let you steam.

**Comment by se-bastiaan** [comment]
We're not Popcorn Time.
