### ISSUE TITLE
Erro gêneros filmes ao.clicar não mostra lista filmes 

### ISSUE THREAD

**Issue by fabiozissou** [butterproject/butter-android#60]
App Version:  
Android version:  

Expected behaviour:
Actual behaviour:

Steps to repoduce the behaviour:

1. ...
2. ...
3. ...

**Comment by fabiozissou** [comment]
Ainda clicar no gênero de filmes não mostra a lista de filmes

**Comment by se-bastiaan** [comment]
English?
