### ISSUE TITLE
Problem with the movieplayer

### ISSUE THREAD

**Issue by hardcrasher** [butterproject/butter-android#61]
App Version:  2.8/3.9
Android version:  4.4.4

Expected behaviour: movie playsperfect
Actual behaviour: the sound is being played, but the screen remains black

Steps to repoduce the behaviour:

1. Choose a movie ( in my case avengers age of ultron or planet of the apes)
2. Start the download and buffering
3. When  the movie starts, i get the sound but no moving picture...

**Comment by se-bastiaan** [comment]
Be aware that we're not Popcorn Time, report your issues in their repository.
