### ISSUE TITLE
The series don't play on my device

### ISSUE THREAD

**Issue by hardcrasher** [butterproject/butter-android#62]
App Version:  2.8/3.9 beta
Android version:  4.4.4

Expected behaviour: tv-series playing like they should play
Actual behaviour: is not working  (mediaplayer gives a error everytime)

Steps to repoduce the behaviour:

1. Choose a serie ( in my case stargate universe / stargate Atlantis / doctor who,...)
2. Download and buffer
3. Look at the screen

**Comment by se-bastiaan** [comment]
Be aware that we're not Popcorn Time, report your issues in their repository.
