### ISSUE TITLE
Torrents are not being loaded.

### ISSUE THREAD

**Issue by hicd07** [butterproject/butter-android#63]
App Version:  0.2.8 - armeabi - v7a
Android version:  5.0.2

Expected behaviour: Load torrents and play a movie.
Actual behaviour: Torrents are not loading. Throwimg a message saying something has gone wrong.

Steps to repoduce the behaviour:

1. Open the app.
2. Select a movie.
3. Click Play button.

**Comment by se-bastiaan** [comment]
Be aware that we're not Popcorn Time, report your issues in their repository.
