### ISSUE TITLE
Big Scrollbar on bottom of video

### ISSUE THREAD

**Issue by Deregtx** [butterproject/butter-android#76]
App Version:  2.8.0
Android version:  6.0.1

Expected behaviour:
Actual behaviour:

Steps to repoduce the behaviour:

1. ... On Chromecast there is a horizontal Scrollbar when playing a video. 
2. ...
3. ...

**Comment by se-bastiaan** [comment]
I don't see how we would be able to fix this.

**Comment by Deregtx** [comment]
It seemed to be only with the first few episodes of the series blunt talk.
Maybe they encoded it wrong.

**Comment by xaiki** [comment]
not a bug in butter.
