### ISSUE TITLE
green screen

### ISSUE THREAD

**Issue by carlosfi** [butterproject/butter-android#79]
App Version:  2.8
Android version:  5.0.2

Expected behaviour:good vision of tv shows
Actual behaviour:
Failure vision of the tv show, the bad vision with a color green
i have a screenshot but i donk now send

Steps to repoduce the behaviour:

1. Just open app
2. Go to shows
3. And try see some show

**Comment by carlosfi** [comment]
![screenshot_2016-08-14-18-06-59](https://cloud.githubusercontent.com/assets/20345240/17652813/66016114-624c-11e6-8875-414962a526e6.png)

**Comment by blazsolar** [comment]
This should be resoled with VLC 3 that we are using now.
