### ISSUE TITLE
All builds fail

### ISSUE THREAD

**Issue by Skehmatics** [butterproject/butter-android#84]
A script that Travis uses to test has been moved, causing every test to fail since 9143eb0b7646156a120628eebd51e83476a60beb

```
$ emulator -avd test -no-skin -no-audio -no-window &
$ curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
$ chmod u+x android-wait-for-emulator
$ ./android-wait-for-emulator
./android-wait-for-emulator: line 1: html: No such file or directory
./android-wait-for-emulator: line 2: syntax error near unexpected token `<'
./android-wait-for-emulator: line 2: `<head><title>301 Moved Permanently</title><script type="text/javascript">'
The command "./android-wait-for-emulator" failed and exited with 2 during .
```

I'm sure this has been noticed already, but I felt an issue necessary to document it.
Maybe try adopting [this cookbook?](https://github.com/travis-ci/travis-cookbooks/tree/master/community-cookbooks/android-sdk)

**Comment by Skehmatics** [comment]
I've taken a quick bit of research and found [this](http://stackoverflow.com/questions/26643444/travis-ci-android-tests-with-gradle-keep-timing-out/)

it looks like the current implementation:
```
curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
chmod u+x android-wait-for-emulator
./android-wait-for-emulator
```

Is a fix for an issue that is [no longer present](http://stackoverflow.com/a/26655171). Replacing it with a call to the included script, `android-wait-for-emulator`, should be sufficient.

**Comment by streger** [comment]
This issue was raised because of failed Travis and then the commit fixed the Travis, and because of that Travis passed the test. This was some Inception style action.
It's safe to close now, I guess. Great detective work @Skehmatics.
